/**
 * Original author abstracts shown on the /issues page, keyed by article id.
 * SITE_ARTICLES carries shorter editorial summaries used elsewhere; this page
 * keeps the authors' own opening text (clamped to four lines in the row).
 */
export const ARTICLE_EXCERPTS: Record<number, string> = {
  10: "This report from the McKinsey Global Institute identifies and describes a category of industries that could account for much of the future change in the business landscape and transform the world. We call these industries arenas of competition. To identify the arenas of tomorrow, we look back at the arenas of today to see how they evolved. Arenas are defined by two characteristics: they capture an outsize share of the economy’s growth, and market share within them changes hands to an outsize degree. The presence of those two attributes indicates that a new competitive game has begun, usually prompted by a new bundle of technologies and business models.",
  1: "The rapidly evolving fields of neuroleadership and neuroeducation hold immense potential for transforming our understanding of effective leadership and learning. While neuroleadership delves into the neural underpinnings of leadership behaviors and decision-making processes (Rock & Schwartz, 2006), neuroeducation bridges the gap between neuroscience and education to optimize learning and cognitive performance (Hardiman, 2012). Despite their distinct origins and focal points, these two fields converge in their shared objective of translating neuroscience research into practical strategies for enhancing human performance and development. In this article, we propose a unified framework that synergizes insights from both domains, leveraging Dr. Mariale Hardiman's Brain-Targeted Teaching (BTT) model to optimize learning and leadership development across organizational and educational contexts.",
  2: "International students in U.S. higher education face increasing uncertainty, not only due to shifting immigration policy and rising xenophobia, but also due to systemic failures in institutional support. This article argues that leadership education—when centered on ethics, creativity, and resilience—is no longer a curriculum enhancement. Drawing on narrative, policy context, and global ethics scholarship, the piece calls for a reimagining of leadership development as a core element of higher education and an essential navigational tool for future leaders. A global moral compass, as defined by Thompson (2010), offers an essential framework for international students navigating complex and inequitable systems.",
  3: "In this article, the author considers physicians' right to refuse to participate in or offer end-of-life care that includes medically assisted death. The author argues that physicians, like patients, are guided by religious and more beliefs, and they do have a right to refuse medically assisted death services if they violate their religious beliefs or moral convictions. To make this case, the author reviews the historical relationship between religion and medicine, looking at how the modern medical system came to be. This helps set the stage for understanding how these two aspects of society affect end-of-life care. Landmark cases in the Right-to-Die movement are presented to further illustrate how religious beliefs affect the care that a person receives at the end of life. After reviewing possible reasons that a physician may object on religious grounds, the author then provides recommendations that honor both the free will of the patient and the physician.",
  4: "Within the public health domain, one of greatest concerns is the rise of addictive behavior among adolescents and young adults. Questions have been raised as to how excessive video gaming, social media overuse of misuse, and online gambling, for instance, present deleterious effects to this population's psychological well-being as well as their overall development. In light of these concerns, public health officials, policymakers, and mental health professionals have set out to explore effective interventions designed to address this issue and improve this population's quality of life and health outcomes. Due to its widespread accessibility, low-cost, relative anonymity, and room for personalization and user engagement, artificial intelligence (AI) is one such intervention currently being explored. This paper therefore joins the ongoing conversation on the potential of AI as a mental health tool used to treat addiction behavior, but is also careful to consider areas of concern in its application.",
  5: "Through the introduction of a tri-part framework focused on commercial, legal, and ethical considerations, this article examines the case of Iceland’s fishing industry to explore key concepts of sustainability. The article focuses on the fishing sector, specifically, as it is poised to grow exponentially in the coming years, as the world looks to more eco-friendly alternatives for land-based meat (e.g., beef, pork). Iceland was selected as the ideal case study for exploring these concepts because not only is the fishing sector well-established within the nation, but because the country’s industry has incorporated environmental, social, and governance (ESG) standards into its operations.",
  6: "This article reviews scholarly literature examining bacteria-plastic interactions to provide insights into the global plastic pollution crisis. Using a PRISMA approach, this review identified and analyzed peer-reviewed studies across multiple databases, including Web of Science, Science Direct, and Google Scholar.",
  7: "This article offers an in-depth look at three high-profile legal cases in which professional athletes were charged with a crime. By examining the cases of football players Henry Ruggs III and Rashee Rice, as well as Olympic wrestler Kyle Snyder, this comparative analysis explores how social and financial capital, institutional response, and media framing all influence the legal process for such elite athletes. Through this exploration, it aims to provide an implicit answer to the question, “Is justice really blind?” By comprehensively investigating the details of each case, this study explores the degree to which the confounding variables of material resources, severity of the resulting harm, and prospect of rehabilitation influences legal outcomes.",
  8: "Combat sports, such as wrestling, boxing, and martials arts, have increased in popularity in recent years, particularly among young people. This increased attention has been mirrored within the scholarly literature on combat sports and their effects on young people’s physical and socioemotional development. The verdict as to whether these impacts have been largely positive or negative, however, remains mixed. This article details the purported benefits of combat sports for youth athletes, citing evidence of value cultivation, protective effects against bullying, and interpersonal competency development. It then proceeds to outline how these competencies connect to improved academic and professional outcomes.",
  9: "This article examines how shifts in golf’s business model and cultural profile are reshaping access to the sport, with particular attention to affordability, public infrastructure, and who benefits from the industry’s growth. It evaluates barriers to entry, the role of municipal courses and youth programs, and the impact of new capital on community access. The piece argues that expansion alone is insufficient without intentional equity and inclusion strategies that ensure the new golf economy serves a broader and more diverse public.",
  11: "This paper presents a quantitative analysis of the implications of natural resource economics on global wealth, encompassing an extensive observational study of growth models from 1970 to 2022 across a diverse set of countries. It scrutinizes the relationships between natural resource rents (as a percentage of Gross Domestic Product) and natural resource depletion (relative to Gross National Income), and their correlation with Gross Domestic Product per capita. The primary aim is to assess whether increased economic prosperity, as derived from natural resources, aligns with sustainable resource management or exacerbates environmental degradation.",
  12: "This perspective piece interrogates the implications of merging religious doctrine with government authority. Using both literary analysis of Arthur Miller’s The Crucible and drawing upon contemporary case studies, this paper argues that theoretical influence over legal systems incites widespread fear, undermines the tenet of due process, and promotes systemic injustice. The three illustrative case studies to be presented here include Stone v. Graham, the Taliban government in Afghanistan, and the proposed policy framework Project 2025.",
  13: "Standardized English proficiency tests such as the Test of English as a Foreign Language (TOEFL) serve as gatekeepers to higher education for millions of students each year, yet the assumption that a single timed test fairly measures a student's ability is seldom examined critically. This review consolidates research on the global testing industry across three connected questions raised by the field: how standardized tests fail diverse learners, how the commercial testing business profits from exclusion, and how assessment might be reimagined beyond a single score.",
  14: "This paper reviews empirical research on algorithmic trading in the U.S. stock market and argues that its effects on price efficiency, transaction costs, and market volatility all stem from a single underlying behavior: the voluntary supply of liquidity by algorithmic and high-frequency trading firms. These firms are not required to keep trading when conditions turn unfavorable, so they supply liquidity when doing so is profitable and withdraw it when it is not. Under ordinary market conditions, this behavior narrows bid-ask spreads, speeds up the incorporation of new information into prices, and lowers trading costs for participants who can move as quickly as the market does.",
  15: "This literature review examines whether bilingual and bicultural students, individuals who grow up speaking two languages and navigating multiple cultural contexts, such as immigrants and green-card holders, possess greater charisma, adaptability, and social capability than their monolingual peers. Drawing on research from cultural psychology, sociolinguistics, and organizational behavior, the review synthesizes findings on cultural intelligence (CQ), cultural frame-switching, code-switching, bicultural identity integration (BII), and the individualism-collectivism dimension.",
  16: "This article examines the erasure of the South Vietnamese perspective in Vietnam War films and documentaries, arguing that this absence distorts public memory and historical understanding of the conflict. While the narratives of American soldiers and North Vietnamese ideologies are frequently centered in cinematic portrayals, the experiences, ideologies, and motivations of the South Vietnamese–those who fought to defend their sovereignty–are often sidelined, stereotyped, or omitted altogether.",
  17: "This research paper evaluates how artificial intelligence, or AI, is changing the way companies around the world come up with new ideas and run their businesses. By looking at over 100 high-quality studies published between 2018 and 2024, we discovered that AI is much more than just a cool new gadget; it is actually a powerful force that is helping businesses create better products, work more efficiently, and understand their customers on a much deeper level.",
};
